// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQUQeZodXezLvV2wso_sXI76ldJ-hjMZk',
    appId: '1:767953128417:web:b4db2c49b172062f7aa0a0',
    messagingSenderId: '767953128417',
    projectId: 'grocery-app-4ca36',
    authDomain: 'grocery-app-4ca36.firebaseapp.com',
    storageBucket: 'grocery-app-4ca36.appspot.com',
    measurementId: 'G-29Y2Z594YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2spPGSYSTXF7VZR0nHthX1IZMwql5Vw',
    appId: '1:767953128417:android:d28a5bd95ecf8a377aa0a0',
    messagingSenderId: '767953128417',
    projectId: 'grocery-app-4ca36',
    storageBucket: 'grocery-app-4ca36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlY8lNyH89uO4vJbpOTIAOrkz54SPWm0I',
    appId: '1:767953128417:ios:5ce6db5325d2986f7aa0a0',
    messagingSenderId: '767953128417',
    projectId: 'grocery-app-4ca36',
    storageBucket: 'grocery-app-4ca36.appspot.com',
    androidClientId: '767953128417-4qts1c0dj27q3ecc6lan9csnentsk1gn.apps.googleusercontent.com',
    iosClientId: '767953128417-55h9k3orgh44404cvalulug86a2pq1ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.users',
  );
}
